//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace FoodOrder.RemoteService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://templater.info/", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeeklyMenu", Namespace="http://templater.info/")]
    public partial class WeeklyMenu : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FoodOrder.RemoteService.ChoiceEnum MenuMarkField;
        
        private string MondayMenuField;
        
        private string TuesdayMenuField;
        
        private string WednesdayMenuField;
        
        private string ThursdayMenuField;
        
        private string FridayMenuField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public FoodOrder.RemoteService.ChoiceEnum MenuMark {
            get {
                return this.MenuMarkField;
            }
            set {
                if ((this.MenuMarkField.Equals(value) != true)) {
                    this.MenuMarkField = value;
                    this.RaisePropertyChanged("MenuMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MondayMenu {
            get {
                return this.MondayMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.MondayMenuField, value) != true)) {
                    this.MondayMenuField = value;
                    this.RaisePropertyChanged("MondayMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TuesdayMenu {
            get {
                return this.TuesdayMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.TuesdayMenuField, value) != true)) {
                    this.TuesdayMenuField = value;
                    this.RaisePropertyChanged("TuesdayMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WednesdayMenu {
            get {
                return this.WednesdayMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.WednesdayMenuField, value) != true)) {
                    this.WednesdayMenuField = value;
                    this.RaisePropertyChanged("WednesdayMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ThursdayMenu {
            get {
                return this.ThursdayMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.ThursdayMenuField, value) != true)) {
                    this.ThursdayMenuField = value;
                    this.RaisePropertyChanged("ThursdayMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FridayMenu {
            get {
                return this.FridayMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.FridayMenuField, value) != true)) {
                    this.FridayMenuField = value;
                    this.RaisePropertyChanged("FridayMenu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChoiceEnum", Namespace="http://templater.info/")]
    public enum ChoiceEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        A = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeMenu", Namespace="http://templater.info/")]
    public partial class EmployeeMenu : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmployeeField;
        
        private FoodOrder.RemoteService.ChoiceEnum MondayChoiceField;
        
        private FoodOrder.RemoteService.ChoiceEnum TuesdayChoiceField;
        
        private FoodOrder.RemoteService.ChoiceEnum WednesdayChoiceField;
        
        private FoodOrder.RemoteService.ChoiceEnum ThursdayChoiceField;
        
        private FoodOrder.RemoteService.ChoiceEnum FridayChoiceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public FoodOrder.RemoteService.ChoiceEnum MondayChoice {
            get {
                return this.MondayChoiceField;
            }
            set {
                if ((this.MondayChoiceField.Equals(value) != true)) {
                    this.MondayChoiceField = value;
                    this.RaisePropertyChanged("MondayChoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public FoodOrder.RemoteService.ChoiceEnum TuesdayChoice {
            get {
                return this.TuesdayChoiceField;
            }
            set {
                if ((this.TuesdayChoiceField.Equals(value) != true)) {
                    this.TuesdayChoiceField = value;
                    this.RaisePropertyChanged("TuesdayChoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public FoodOrder.RemoteService.ChoiceEnum WednesdayChoice {
            get {
                return this.WednesdayChoiceField;
            }
            set {
                if ((this.WednesdayChoiceField.Equals(value) != true)) {
                    this.WednesdayChoiceField = value;
                    this.RaisePropertyChanged("WednesdayChoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public FoodOrder.RemoteService.ChoiceEnum ThursdayChoice {
            get {
                return this.ThursdayChoiceField;
            }
            set {
                if ((this.ThursdayChoiceField.Equals(value) != true)) {
                    this.ThursdayChoiceField = value;
                    this.RaisePropertyChanged("ThursdayChoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public FoodOrder.RemoteService.ChoiceEnum FridayChoice {
            get {
                return this.FridayChoiceField;
            }
            set {
                if ((this.FridayChoiceField.Equals(value) != true)) {
                    this.FridayChoiceField = value;
                    this.RaisePropertyChanged("FridayChoice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://templater.info/", ConfigurationName="RemoteService.MainServiceSoap")]
    public interface MainServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://templater.info/GetEmployees", ReplyAction="*")]
        System.IAsyncResult BeginGetEmployees(FoodOrder.RemoteService.GetEmployeesRequest request, System.AsyncCallback callback, object asyncState);
        
        FoodOrder.RemoteService.GetEmployeesResponse EndGetEmployees(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://templater.info/GetMenus", ReplyAction="*")]
        System.IAsyncResult BeginGetMenus(FoodOrder.RemoteService.GetMenusRequest request, System.AsyncCallback callback, object asyncState);
        
        FoodOrder.RemoteService.GetMenusResponse EndGetMenus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://templater.info/CreateReport", ReplyAction="*")]
        System.IAsyncResult BeginCreateReport(FoodOrder.RemoteService.CreateReportRequest request, System.AsyncCallback callback, object asyncState);
        
        FoodOrder.RemoteService.CreateReportResponse EndCreateReport(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://templater.info/", Order=0)]
        public FoodOrder.RemoteService.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(FoodOrder.RemoteService.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://templater.info/", Order=0)]
        public FoodOrder.RemoteService.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(FoodOrder.RemoteService.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://templater.info/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FoodOrder.RemoteService.ArrayOfString GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(FoodOrder.RemoteService.ArrayOfString GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMenusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMenus", Namespace="http://templater.info/", Order=0)]
        public FoodOrder.RemoteService.GetMenusRequestBody Body;
        
        public GetMenusRequest() {
        }
        
        public GetMenusRequest(FoodOrder.RemoteService.GetMenusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMenusRequestBody {
        
        public GetMenusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMenusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMenusResponse", Namespace="http://templater.info/", Order=0)]
        public FoodOrder.RemoteService.GetMenusResponseBody Body;
        
        public GetMenusResponse() {
        }
        
        public GetMenusResponse(FoodOrder.RemoteService.GetMenusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://templater.info/")]
    public partial class GetMenusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.WeeklyMenu> GetMenusResult;
        
        public GetMenusResponseBody() {
        }
        
        public GetMenusResponseBody(System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.WeeklyMenu> GetMenusResult) {
            this.GetMenusResult = GetMenusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateReport", Namespace="http://templater.info/", Order=0)]
        public FoodOrder.RemoteService.CreateReportRequestBody Body;
        
        public CreateReportRequest() {
        }
        
        public CreateReportRequest(FoodOrder.RemoteService.CreateReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://templater.info/")]
    public partial class CreateReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.EmployeeMenu> choices;
        
        public CreateReportRequestBody() {
        }
        
        public CreateReportRequestBody(string customer, System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.EmployeeMenu> choices) {
            this.customer = customer;
            this.choices = choices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateReportResponse", Namespace="http://templater.info/", Order=0)]
        public FoodOrder.RemoteService.CreateReportResponseBody Body;
        
        public CreateReportResponse() {
        }
        
        public CreateReportResponse(FoodOrder.RemoteService.CreateReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://templater.info/")]
    public partial class CreateReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateReportResult;
        
        public CreateReportResponseBody() {
        }
        
        public CreateReportResponseBody(string CreateReportResult) {
            this.CreateReportResult = CreateReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainServiceSoapChannel : FoodOrder.RemoteService.MainServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FoodOrder.RemoteService.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FoodOrder.RemoteService.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMenusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMenusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.WeeklyMenu> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.WeeklyMenu>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServiceSoapClient : System.ServiceModel.ClientBase<FoodOrder.RemoteService.MainServiceSoap>, FoodOrder.RemoteService.MainServiceSoap {
        
        private BeginOperationDelegate onBeginGetEmployeesDelegate;
        
        private EndOperationDelegate onEndGetEmployeesDelegate;
        
        private System.Threading.SendOrPostCallback onGetEmployeesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMenusDelegate;
        
        private EndOperationDelegate onEndGetMenusDelegate;
        
        private System.Threading.SendOrPostCallback onGetMenusCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateReportDelegate;
        
        private EndOperationDelegate onEndCreateReportDelegate;
        
        private System.Threading.SendOrPostCallback onCreateReportCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MainServiceSoapClient() {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetEmployeesCompletedEventArgs> GetEmployeesCompleted;
        
        public event System.EventHandler<GetMenusCompletedEventArgs> GetMenusCompleted;
        
        public event System.EventHandler<CreateReportCompletedEventArgs> CreateReportCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FoodOrder.RemoteService.MainServiceSoap.BeginGetEmployees(FoodOrder.RemoteService.GetEmployeesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEmployees(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetEmployees(System.AsyncCallback callback, object asyncState) {
            FoodOrder.RemoteService.GetEmployeesRequest inValue = new FoodOrder.RemoteService.GetEmployeesRequest();
            inValue.Body = new FoodOrder.RemoteService.GetEmployeesRequestBody();
            return ((FoodOrder.RemoteService.MainServiceSoap)(this)).BeginGetEmployees(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FoodOrder.RemoteService.GetEmployeesResponse FoodOrder.RemoteService.MainServiceSoap.EndGetEmployees(System.IAsyncResult result) {
            return base.Channel.EndGetEmployees(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private FoodOrder.RemoteService.ArrayOfString EndGetEmployees(System.IAsyncResult result) {
            FoodOrder.RemoteService.GetEmployeesResponse retVal = ((FoodOrder.RemoteService.MainServiceSoap)(this)).EndGetEmployees(result);
            return retVal.Body.GetEmployeesResult;
        }
        
        private System.IAsyncResult OnBeginGetEmployees(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetEmployees(callback, asyncState);
        }
        
        private object[] OnEndGetEmployees(System.IAsyncResult result) {
            FoodOrder.RemoteService.ArrayOfString retVal = this.EndGetEmployees(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEmployeesCompleted(object state) {
            if ((this.GetEmployeesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEmployeesCompleted(this, new GetEmployeesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEmployeesAsync() {
            this.GetEmployeesAsync(null);
        }
        
        public void GetEmployeesAsync(object userState) {
            if ((this.onBeginGetEmployeesDelegate == null)) {
                this.onBeginGetEmployeesDelegate = new BeginOperationDelegate(this.OnBeginGetEmployees);
            }
            if ((this.onEndGetEmployeesDelegate == null)) {
                this.onEndGetEmployeesDelegate = new EndOperationDelegate(this.OnEndGetEmployees);
            }
            if ((this.onGetEmployeesCompletedDelegate == null)) {
                this.onGetEmployeesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEmployeesCompleted);
            }
            base.InvokeAsync(this.onBeginGetEmployeesDelegate, null, this.onEndGetEmployeesDelegate, this.onGetEmployeesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FoodOrder.RemoteService.MainServiceSoap.BeginGetMenus(FoodOrder.RemoteService.GetMenusRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMenus(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetMenus(System.AsyncCallback callback, object asyncState) {
            FoodOrder.RemoteService.GetMenusRequest inValue = new FoodOrder.RemoteService.GetMenusRequest();
            inValue.Body = new FoodOrder.RemoteService.GetMenusRequestBody();
            return ((FoodOrder.RemoteService.MainServiceSoap)(this)).BeginGetMenus(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FoodOrder.RemoteService.GetMenusResponse FoodOrder.RemoteService.MainServiceSoap.EndGetMenus(System.IAsyncResult result) {
            return base.Channel.EndGetMenus(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.WeeklyMenu> EndGetMenus(System.IAsyncResult result) {
            FoodOrder.RemoteService.GetMenusResponse retVal = ((FoodOrder.RemoteService.MainServiceSoap)(this)).EndGetMenus(result);
            return retVal.Body.GetMenusResult;
        }
        
        private System.IAsyncResult OnBeginGetMenus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetMenus(callback, asyncState);
        }
        
        private object[] OnEndGetMenus(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.WeeklyMenu> retVal = this.EndGetMenus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMenusCompleted(object state) {
            if ((this.GetMenusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMenusCompleted(this, new GetMenusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMenusAsync() {
            this.GetMenusAsync(null);
        }
        
        public void GetMenusAsync(object userState) {
            if ((this.onBeginGetMenusDelegate == null)) {
                this.onBeginGetMenusDelegate = new BeginOperationDelegate(this.OnBeginGetMenus);
            }
            if ((this.onEndGetMenusDelegate == null)) {
                this.onEndGetMenusDelegate = new EndOperationDelegate(this.OnEndGetMenus);
            }
            if ((this.onGetMenusCompletedDelegate == null)) {
                this.onGetMenusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMenusCompleted);
            }
            base.InvokeAsync(this.onBeginGetMenusDelegate, null, this.onEndGetMenusDelegate, this.onGetMenusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FoodOrder.RemoteService.MainServiceSoap.BeginCreateReport(FoodOrder.RemoteService.CreateReportRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateReport(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCreateReport(string customer, System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.EmployeeMenu> choices, System.AsyncCallback callback, object asyncState) {
            FoodOrder.RemoteService.CreateReportRequest inValue = new FoodOrder.RemoteService.CreateReportRequest();
            inValue.Body = new FoodOrder.RemoteService.CreateReportRequestBody();
            inValue.Body.customer = customer;
            inValue.Body.choices = choices;
            return ((FoodOrder.RemoteService.MainServiceSoap)(this)).BeginCreateReport(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FoodOrder.RemoteService.CreateReportResponse FoodOrder.RemoteService.MainServiceSoap.EndCreateReport(System.IAsyncResult result) {
            return base.Channel.EndCreateReport(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndCreateReport(System.IAsyncResult result) {
            FoodOrder.RemoteService.CreateReportResponse retVal = ((FoodOrder.RemoteService.MainServiceSoap)(this)).EndCreateReport(result);
            return retVal.Body.CreateReportResult;
        }
        
        private System.IAsyncResult OnBeginCreateReport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string customer = ((string)(inValues[0]));
            System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.EmployeeMenu> choices = ((System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.EmployeeMenu>)(inValues[1]));
            return this.BeginCreateReport(customer, choices, callback, asyncState);
        }
        
        private object[] OnEndCreateReport(System.IAsyncResult result) {
            string retVal = this.EndCreateReport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateReportCompleted(object state) {
            if ((this.CreateReportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateReportCompleted(this, new CreateReportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateReportAsync(string customer, System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.EmployeeMenu> choices) {
            this.CreateReportAsync(customer, choices, null);
        }
        
        public void CreateReportAsync(string customer, System.Collections.ObjectModel.ObservableCollection<FoodOrder.RemoteService.EmployeeMenu> choices, object userState) {
            if ((this.onBeginCreateReportDelegate == null)) {
                this.onBeginCreateReportDelegate = new BeginOperationDelegate(this.OnBeginCreateReport);
            }
            if ((this.onEndCreateReportDelegate == null)) {
                this.onEndCreateReportDelegate = new EndOperationDelegate(this.OnEndCreateReport);
            }
            if ((this.onCreateReportCompletedDelegate == null)) {
                this.onCreateReportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateReportCompleted);
            }
            base.InvokeAsync(this.onBeginCreateReportDelegate, new object[] {
                        customer,
                        choices}, this.onEndCreateReportDelegate, this.onCreateReportCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override FoodOrder.RemoteService.MainServiceSoap CreateChannel() {
            return new MainServiceSoapClientChannel(this);
        }
        
        private class MainServiceSoapClientChannel : ChannelBase<FoodOrder.RemoteService.MainServiceSoap>, FoodOrder.RemoteService.MainServiceSoap {
            
            public MainServiceSoapClientChannel(System.ServiceModel.ClientBase<FoodOrder.RemoteService.MainServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetEmployees(FoodOrder.RemoteService.GetEmployeesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetEmployees", _args, callback, asyncState);
                return _result;
            }
            
            public FoodOrder.RemoteService.GetEmployeesResponse EndGetEmployees(System.IAsyncResult result) {
                object[] _args = new object[0];
                FoodOrder.RemoteService.GetEmployeesResponse _result = ((FoodOrder.RemoteService.GetEmployeesResponse)(base.EndInvoke("GetEmployees", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMenus(FoodOrder.RemoteService.GetMenusRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetMenus", _args, callback, asyncState);
                return _result;
            }
            
            public FoodOrder.RemoteService.GetMenusResponse EndGetMenus(System.IAsyncResult result) {
                object[] _args = new object[0];
                FoodOrder.RemoteService.GetMenusResponse _result = ((FoodOrder.RemoteService.GetMenusResponse)(base.EndInvoke("GetMenus", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateReport(FoodOrder.RemoteService.CreateReportRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CreateReport", _args, callback, asyncState);
                return _result;
            }
            
            public FoodOrder.RemoteService.CreateReportResponse EndCreateReport(System.IAsyncResult result) {
                object[] _args = new object[0];
                FoodOrder.RemoteService.CreateReportResponse _result = ((FoodOrder.RemoteService.CreateReportResponse)(base.EndInvoke("CreateReport", _args, result)));
                return _result;
            }
        }
    }
}
